"""
Vendors brand icon paths into tools/icons.py.

Source is the simple-icons npm package (CC0, no attribution required). The
paths must be vendored rather than referenced: camo serves README images with
external fetches blocked, so an icon only renders if its path data is inlined
in the SVG itself. Committing icons.py also keeps CI deterministic and offline.

Run once, or again to refresh:  python tools/fetch_icons.py
"""

import re
import urllib.request
from pathlib import Path

# key -> (candidate slugs tried in order, display label)
WANT = {
    "python": (["python"], "Python"),
    "typescript": (["typescript"], "TypeScript"),
    "php": (["php"], "PHP"),
    "fastapi": (["fastapi"], "FastAPI"),
    "nextdotjs": (["nextdotjs"], "Next.js"),
    "tailwindcss": (["tailwindcss"], "Tailwind"),
    "mariadb": (["mariadb"], "MariaDB"),
    "postgresql": (["postgresql"], "Postgres"),
    "stripe": (["stripe"], "Stripe"),
    "openai": (["openai"], "OpenAI"),
    "claude": (["claude", "anthropic"], "Claude"),
    "discord": (["discord"], "Discord"),
}

CDNS = [
    "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/{}.svg",
    "https://unpkg.com/simple-icons@latest/icons/{}.svg",
]


def fetch(slug: str) -> str | None:
    for cdn in CDNS:
        try:
            request = urllib.request.Request(
                cdn.format(slug), headers={"User-Agent": "profile-icons"}
            )
            with urllib.request.urlopen(request, timeout=30) as response:
                svg = response.read().decode()
            match = re.search(r'\bd="([^"]+)"', svg)
            if match:
                return match.group(1)
        except Exception:
            continue
    return None


def main():
    out = {}
    for key, (slugs, label) in WANT.items():
        path = next((p for slug in slugs if (p := fetch(slug))), None)
        if not path:
            raise SystemExit(f"no icon found for {key} (tried {slugs})")
        out[key] = (label, path)
        print(f"{key:12} ok ({len(path)} chars)")

    target = Path(__file__).resolve().parent / "icons.py"
    lines = [
        '"""Vendored Simple Icons path data (24x24 viewBox, CC0).',
        "",
        "Generated by tools/fetch_icons.py; edit that, not this.",
        '"""',
        "",
        "ICONS = {",
    ]
    for key, (label, path) in out.items():
        lines.append(f'    "{key}": ({label!r}, "{path}"),')
    lines.append("}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
